# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            managers=[
                ('EmailManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
